In [1]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
# Create a vector with values ranging from 10 to 49.
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Create a 3x3 matrix with values ranging from 0 to 8
c=np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
d=np.nonzero([1,2,0,0,4,0])
print(d)

(array([0, 1, 4], dtype=int64),)


In [9]:
#Create a 10x10 array with random values and find the minimum and maximum values.
e=np.random.random((10,10))
emin,emax=e.min(),e.max()
print( "minimum value is", emin)
print( "maximum value is", emax)

minimum value is 0.0175316915598398
maximum value is 0.99773795636007


In [15]:
#Create a random vector of size 30 and find the mean value.
f= np.random.random(30)

print(f.mean)

<built-in method mean of numpy.ndarray object at 0x00000259A86F1170>
